/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health probe
         * @description Basic uptime signal for monitoring.
         */
        get: operations["health_probe_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tariffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Derniers tarifs frais
         * @description Expose `/v1/tariffs` tel que decrit dans `specs/api.md`.
         */
        get: operations["get_latest_tariffs_v1_tariffs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tariffs/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historique insert-only */
        get: operations["get_tariff_history_v1_tariffs_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/guards/trve-diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ecart vs TRVE
         * @description Return last validation snapshot between observed tariffs and TRVE reference.
         */
        get: operations["get_trve_diff_v1_guards_trve_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * FreshnessStatus
         * @enum {string}
         */
        FreshnessStatus: "fresh" | "verifying" | "stale" | "broken";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** TariffCollection */
        TariffCollection: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Items */
            items: components["schemas"]["TariffObservation"][];
        };
        /** TariffHistoryFilters */
        TariffHistoryFilters: {
            /** Supplier */
            supplier?: string | null;
            option?: components["schemas"]["TariffOption"] | null;
            /** Puissance Kva */
            puissance_kva?: (3 | 6 | 9 | 12 | 15 | 18 | 24 | 30 | 36) | null;
            /** Since */
            since?: string | null;
            /** Until */
            until?: string | null;
        };
        /** TariffHistoryResponse */
        TariffHistoryResponse: {
            filters: components["schemas"]["TariffHistoryFilters"];
            /** Items */
            items: components["schemas"]["TariffObservation"][];
        };
        /** TariffObservation */
        TariffObservation: {
            /**
             * Supplier
             * @description Supplier name as published in the spec
             */
            supplier: string;
            option: components["schemas"]["TariffOption"];
            /**
             * Puissance Kva
             * @enum {integer}
             */
            puissance_kva: 3 | 6 | 9 | 12 | 15 | 18 | 24 | 30 | 36;
            /** Price Kwh Ttc */
            price_kwh_ttc?: number | null;
            /** Price Kwh Hp Ttc */
            price_kwh_hp_ttc?: number | null;
            /** Price Kwh Hc Ttc */
            price_kwh_hc_ttc?: number | null;
            /** Abo Month Ttc */
            abo_month_ttc: number;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Parser Version */
            parser_version: string;
            /** Source Url */
            source_url: string;
            /** Source Checksum */
            source_checksum: string;
            /** @description fresh/verifying/stale/broken per constitution */
            data_status: components["schemas"]["FreshnessStatus"];
            /** Last Verified */
            last_verified?: string | null;
        };
        /**
         * TariffOption
         * @enum {string}
         */
        TariffOption: "BASE" | "HPHC" | "TEMPO";
        /** TrveDiffEntry */
        TrveDiffEntry: {
            /** Supplier */
            supplier: string;
            option: components["schemas"]["TariffOption"];
            /**
             * Puissance Kva
             * @enum {integer}
             */
            puissance_kva: 3 | 6 | 9 | 12 | 15 | 18 | 24 | 30 | 36;
            /** Delta Eur Per Mwh */
            delta_eur_per_mwh: number;
            /**
             * Compared At
             * Format: date-time
             */
            compared_at: string;
            /**
             * Status
             * @description ok|alert per TRVE guard
             */
            status: string;
        };
        /** TrveDiffResponse */
        TrveDiffResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Items */
            items: components["schemas"]["TrveDiffEntry"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_probe_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_latest_tariffs_v1_tariffs_get: {
        parameters: {
            query?: {
                /** @description Filtrer par option tarifaire */
                option?: components["schemas"]["TariffOption"] | null;
                /** @description Limiter a une puissance specifique (kVA) */
                puissance?: number | null;
                /** @description Inclure les observations marquees stale/broken pour audit */
                include_stale?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TariffCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tariff_history_v1_tariffs_history_get: {
        parameters: {
            query?: {
                /** @description Filtrer par fournisseur */
                supplier?: string | null;
                option?: components["schemas"]["TariffOption"] | null;
                puissance?: number | null;
                /** @description Inclure les observations a partir de cette date */
                since?: string | null;
                /** @description Inclure les observations jusqu'a cette date */
                until?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TariffHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trve_diff_v1_guards_trve_diff_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrveDiffResponse"];
                };
            };
        };
    };
}
